ALTER TABLE player_vehicles ADD COLUMN IF NOT EXISTS `engine` INT(11) NOT NULL DEFAULT '1000';
ALTER TABLE player_vehicles ADD COLUMN IF NOT EXISTS `body` INT(11) NOT NULL DEFAULT '1000';
ALTER TABLE player_vehicles ADD COLUMN IF NOT EXISTS `fuel` INT(11) NOT NULL DEFAULT '100';
